// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs9-92oxUQVmDKSZ-C6sgxHZgCBrhEIdk',
    appId: '1:368439345338:web:3a44e492bf2a6126018283',
    messagingSenderId: '368439345338',
    projectId: 'product-fidelite-ankk',
    authDomain: 'product-fidelite-ankk.firebaseapp.com',
    storageBucket: 'product-fidelite-ankk.firebasestorage.app',
    measurementId: 'G-RGL2C4B09S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0CH9EzLijOA9a20DstIFuEy8oLL0C0Rw',
    appId: '1:368439345338:android:229a6bebdc44313a018283',
    messagingSenderId: '368439345338',
    projectId: 'product-fidelite-ankk',
    storageBucket: 'product-fidelite-ankk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAb4cbgYwqFABxHjoejSBQOC7vB_ziFrc',
    appId: '1:368439345338:ios:b628a8353b495ef7018283',
    messagingSenderId: '368439345338',
    projectId: 'product-fidelite-ankk',
    storageBucket: 'product-fidelite-ankk.firebasestorage.app',
    iosBundleId: 'com.ankk.fidelite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAb4cbgYwqFABxHjoejSBQOC7vB_ziFrc',
    appId: '1:368439345338:ios:b628a8353b495ef7018283',
    messagingSenderId: '368439345338',
    projectId: 'product-fidelite-ankk',
    storageBucket: 'product-fidelite-ankk.firebasestorage.app',
    iosBundleId: 'com.ankk.fidelite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs9-92oxUQVmDKSZ-C6sgxHZgCBrhEIdk',
    appId: '1:368439345338:web:a40973e7a995d64a018283',
    messagingSenderId: '368439345338',
    projectId: 'product-fidelite-ankk',
    authDomain: 'product-fidelite-ankk.firebaseapp.com',
    storageBucket: 'product-fidelite-ankk.firebasestorage.app',
    measurementId: 'G-99DKY290RB',
  );
}
